### ISSUE TITLE
Adding leading whitespaces in load_assignment on load-balancing#step2

### ISSUE THREAD

**Issue by policeman-kh** [envoyproxy/katacoda-scenarios#18]
Hello. 
Can I share suggestion about the scenario of "Controlling load balancing policies" ?
I tried this scenario and got an error
> curl: (7) Failed to connect to localhost port 80: Connect

on step 3.
The reason was that the "load_assignment" copied in step2 does not have leading spaces.
<img width="300" alt="screenshop" src="https://user-images.githubusercontent.com/20625903/90143997-3bc9f180-ddb9-11ea-92cf-091472f6a6b7.png">

Maybe most users will just copy it.
So I think it is better to put leading whitespaces in the load_assignment.
https://github.com/envoyproxy/katacoda-scenarios/blame/master/load-balancing/step2.md#L9-L24
Like
```
    load_assignment:
      cluster_name: targetCluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.18.0.3
                port_value: 80
        load_balancing_weight: 90
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.18.0.4
                port_value: 80
```
